/*
 * File: app/view/Monitee/AddForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.Monitee.AddForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.moniteeform',

    hidden: false,
    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                this.up('form').getForm().reset();
                            },
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'add_monitee_button',
                            text: 'Submit',
                            formBind: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});