/*
 * File: app/view/Monitee/Choose.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.Monitee.Choose', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.choosemonitee',

    layout: {
        type: 'anchor'
    },
    title: 'Add New Monitee',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'dataview',
                    id: 'monitees-view',
                    tpl: [
                        '<tpl for="."><div class="thumb-wrap"><div class="thumb" data-qtip="{tip}" ><img src="resources/icons/monitees/{icon}" /><span>{name}</span></div></div></tpl>'
                    ],
                    itemSelector: '.thumb-wrap',
                    overItemCls: 'x-view-over',
                    store: 'MoniteeListStore',
                    trackOver: true
                }
            ]
        });

        me.callParent(arguments);
    }

});