/*
 * File: app/view/Monitee/VimForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.Monitee.VimForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.moniteevimform',

    bodyPadding: 10,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'textfield',
                    name: 'ip',
                    fieldLabel: 'IP',
                    anchor: '100%'
                },
                {
                    xtype: 'combobox',
                    name: 'phym_id',
                    fieldLabel: 'Physical Machine',
                    displayField: 'id',
                    store: 'Phym',
                    valueField: 'id',
                    anchor: '100%'
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    ui: 'footer',
                    dock: 'bottom',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                this.up('form').getForm().reset();
                            },
                            text: 'Reset'
                        },
                        {
                            xtype: 'button',
                            disabled: true,
                            id: 'save_vim_button',
                            text: 'Submit',
                            formBind: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});