/*
 * File: app/controller/MenuController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.controller.MenuController', {
    extend: 'Ext.app.Controller',

    views: [
        'Navigation',
        'ContentPanel'
    ],

    refs: [
        {
            ref: 'contentPanel',
            selector: 'contentpanel'
        }
    ],

    init: function(application) {
        this.control({
            'navigation dataview': {
                selectionchange: this.switchView
            }

        });
    },

    switchView: function(selModel, selected) {
        if(selected.length > 0){
            var index = selected[0].data.id;
            this.getContentPanel().layout.setActiveItem(index);
        }
    }

});
