/*
 * File: app/controller/ModelController.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.controller.ModelController', {
    extend: 'Ext.app.Controller',

    views: [
        'ModelDefPanel',
        'ModelViewPanel'
    ],

    init: function(application) {
        this.control({			
            'modeldefpanel' : {
                beforerender : this.draw
            }
        });

    },

    draw: function() {
        /*
        main(document.getElementById('graphContainer'),
        document.getElementById('outlineContainer'),
        document.getElementById('toolbarContainer'),
        document.getElementById('sidebarContainer'),
        document.getElementById('statusContainer'));
        */
    },

    loadModel: function() {

        Ext.Ajax.request({
            url: 'model/getmodel',                
            success: function(response){
                var json = response.responseText;
                var phyms = Ext.decode(json);
                //generateModel(document.getElementById('runtimemodel_graph_container'),modelData);
            },
            failure: function(response){
            }
        });


    }

});
