// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import javax.persistence.Entity;
import org.seforge.paas.monitor.domain.Apache;

privileged aspect Apache_Roo_Jpa_Entity {
    
    declare @type: Apache: @Entity;
    
}
