// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.io.Serializable;

privileged aspect MBeanAttribute_Roo_Serializable {
    
    declare parents: MBeanAttribute implements Serializable;
    
    private static final long MBeanAttribute.serialVersionUID = 1L;
    
}
