// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import org.seforge.paas.monitor.domain.MBeanAttribute;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MBeanAttribute_Roo_Configurable {
    
    declare @type: MBeanAttribute: @Configurable;
    
}
