/*
 * File: app/view/ModelViewPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.ModelViewPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.modelviewpanel',

    layout: {
        type: 'border'
    },
    title: 'View Model',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    contentEl: 'runtimemodel_graph_container',
                    autoScroll: true,
                    title: 'Runtime Model',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    contentEl: 'runtimemodel_status_container',
                    height: 60,
                    title: 'Status',
                    region: 'south'
                },
                {
                    xtype: 'panel',
                    contentEl: 'runtimemodel_outline_container',
                    width: 150,
                    title: 'Outline',
                    region: 'east'
                },
                {
                    xtype: 'panel',
                    contentEl: 'runtimemodel_toolbar_container',
                    height: 60,
                    title: 'Toolbar',
                    region: 'north'
                }
            ]
        });

        me.callParent(arguments);
    }

});