/*
 * File: app/view/ModelDefPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.ModelDefPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.modeldefpanel',

    height: 250,
    width: 400,
    layout: {
        type: 'border'
    },
    title: 'Define Model',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    contentEl: 'toolbarContainer',
                    height: 50,
                    title: 'Toolbar',
                    region: 'north'
                },
                {
                    xtype: 'panel',
                    contentEl: 'sidebarContainer',
                    width: 60,
                    title: 'Monitee',
                    region: 'west'
                },
                {
                    xtype: 'panel',
                    contentEl: 'graphContainer',
                    title: 'Diagram',
                    region: 'center'
                },
                {
                    xtype: 'panel',
                    contentEl: 'statusContainer',
                    height: 30,
                    region: 'south'
                },
                {
                    xtype: 'panel',
                    contentEl: 'outlineContainer',
                    width: 150,
                    title: 'My Panel',
                    region: 'east'
                }
            ]
        });

        me.callParent(arguments);
    }

});