/*
 * File: app/view/Navigation.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('PaaSMonitor.view.Navigation', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.navigation',

    width: 150,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    collapsible: true,
    title: 'Navigation',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'dataview',
                    cls: 'menu-list',
                    id: 'menu-view',
                    tpl: [
                        '<tpl for="."><div class="menu-list-item"><span class="menu-icon"><img src="resources/icons/menu/{icon}" /></span>{name}</div></tpl>'
                    ],
                    itemSelector: '.menu-list-item',
                    overItemCls: 'menu-list-item-hover ',
                    singleSelect: true,
                    store: 'MenuStore',
                    trackOver: true,
                    flex: 1
                }
            ]
        });

        me.callParent(arguments);
    }

});