// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.seforge.paas.monitor.domain.App;
import org.seforge.paas.monitor.domain.AppDataOnDemand;
import org.seforge.paas.monitor.domain.PaasUser;
import org.springframework.stereotype.Component;

privileged aspect AppDataOnDemand_Roo_DataOnDemand {
    
    declare @type: AppDataOnDemand: @Component;
    
    private Random AppDataOnDemand.rnd = new SecureRandom();
    
    private List<App> AppDataOnDemand.data;
    
    public App AppDataOnDemand.getNewTransientApp(int index) {
        App obj = new App();
        setName(obj, index);
        setPaasUser(obj, index);
        return obj;
    }
    
    public void AppDataOnDemand.setName(App obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void AppDataOnDemand.setPaasUser(App obj, int index) {
        PaasUser paasUser = null;
        obj.setPaasUser(paasUser);
    }
    
    public App AppDataOnDemand.getSpecificApp(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        App obj = data.get(index);
        Long id = obj.getId();
        return App.findApp(id);
    }
    
    public App AppDataOnDemand.getRandomApp() {
        init();
        App obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return App.findApp(id);
    }
    
    public boolean AppDataOnDemand.modifyApp(App obj) {
        return false;
    }
    
    public void AppDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = App.findAppEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'App' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<App>();
        for (int i = 0; i < 10; i++) {
            App obj = getNewTransientApp(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
