// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.AppInstance;
import org.seforge.paas.monitor.domain.AppInstanceDataOnDemand;
import org.seforge.paas.monitor.domain.AppInstanceIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppInstanceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppInstanceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppInstanceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppInstanceIntegrationTest: @Transactional;
    
    @Autowired
    private AppInstanceDataOnDemand AppInstanceIntegrationTest.dod;
    
    @Test
    public void AppInstanceIntegrationTest.testCountAppInstances() {
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", dod.getRandomAppInstance());
        long count = AppInstance.countAppInstances();
        Assert.assertTrue("Counter for 'AppInstance' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppInstanceIntegrationTest.testFindAppInstance() {
        AppInstance obj = dod.getRandomAppInstance();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to provide an identifier", id);
        obj = AppInstance.findAppInstance(id);
        Assert.assertNotNull("Find method for 'AppInstance' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppInstance' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppInstanceIntegrationTest.testFindAllAppInstances() {
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", dod.getRandomAppInstance());
        long count = AppInstance.countAppInstances();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppInstance', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppInstance> result = AppInstance.findAllAppInstances();
        Assert.assertNotNull("Find all method for 'AppInstance' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppInstance' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppInstanceIntegrationTest.testFindAppInstanceEntries() {
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", dod.getRandomAppInstance());
        long count = AppInstance.countAppInstances();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppInstance> result = AppInstance.findAppInstanceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppInstance' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppInstance' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppInstanceIntegrationTest.testFlush() {
        AppInstance obj = dod.getRandomAppInstance();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to provide an identifier", id);
        obj = AppInstance.findAppInstance(id);
        Assert.assertNotNull("Find method for 'AppInstance' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppInstance(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppInstance' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppInstanceIntegrationTest.testMergeUpdate() {
        AppInstance obj = dod.getRandomAppInstance();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to provide an identifier", id);
        obj = AppInstance.findAppInstance(id);
        boolean modified =  dod.modifyAppInstance(obj);
        Integer currentVersion = obj.getVersion();
        AppInstance merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppInstance' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppInstanceIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", dod.getRandomAppInstance());
        AppInstance obj = dod.getNewTransientAppInstance(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppInstance' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppInstance' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppInstanceIntegrationTest.testRemove() {
        AppInstance obj = dod.getRandomAppInstance();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppInstance' failed to provide an identifier", id);
        obj = AppInstance.findAppInstance(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppInstance' with identifier '" + id + "'", AppInstance.findAppInstance(id));
    }
    
}
