// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.AppDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AppIntegrationTest: @Transactional;
    
    @Autowired
    private AppDataOnDemand AppIntegrationTest.dod;
    
    @Test
    public void AppIntegrationTest.testCountApps() {
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", dod.getRandomApp());
        long count = org.seforge.paas.monitor.domain.App.countApps();
        org.junit.Assert.assertTrue("Counter for 'App' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppIntegrationTest.testFindApp() {
        org.seforge.paas.monitor.domain.App obj = dod.getRandomApp();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.App.findApp(id);
        org.junit.Assert.assertNotNull("Find method for 'App' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'App' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppIntegrationTest.testFindAllApps() {
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", dod.getRandomApp());
        long count = org.seforge.paas.monitor.domain.App.countApps();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'App', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.seforge.paas.monitor.domain.App> result = org.seforge.paas.monitor.domain.App.findAllApps();
        org.junit.Assert.assertNotNull("Find all method for 'App' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'App' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppIntegrationTest.testFindAppEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", dod.getRandomApp());
        long count = org.seforge.paas.monitor.domain.App.countApps();
        if (count > 20) count = 20;
        java.util.List<org.seforge.paas.monitor.domain.App> result = org.seforge.paas.monitor.domain.App.findAppEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'App' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'App' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppIntegrationTest.testFlush() {
        org.seforge.paas.monitor.domain.App obj = dod.getRandomApp();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.App.findApp(id);
        org.junit.Assert.assertNotNull("Find method for 'App' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'App' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppIntegrationTest.testMerge() {
        org.seforge.paas.monitor.domain.App obj = dod.getRandomApp();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.App.findApp(id);
        boolean modified =  dod.modifyApp(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.seforge.paas.monitor.domain.App merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'App' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", dod.getRandomApp());
        org.seforge.paas.monitor.domain.App obj = dod.getNewTransientApp(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'App' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'App' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppIntegrationTest.testRemove() {
        org.seforge.paas.monitor.domain.App obj = dod.getRandomApp();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'App' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.App.findApp(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'App' with identifier '" + id + "'", org.seforge.paas.monitor.domain.App.findApp(id));
    }
    
}
