// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.AppServer;
import org.seforge.paas.monitor.domain.AppServerDataOnDemand;
import org.seforge.paas.monitor.domain.AppServerIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AppServerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AppServerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AppServerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: AppServerIntegrationTest: @Transactional;
    
    @Autowired
    private AppServerDataOnDemand AppServerIntegrationTest.dod;
    
    @Test
    public void AppServerIntegrationTest.testCountAppServers() {
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", dod.getRandomAppServer());
        long count = AppServer.countAppServers();
        Assert.assertTrue("Counter for 'AppServer' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AppServerIntegrationTest.testFindAppServer() {
        AppServer obj = dod.getRandomAppServer();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to provide an identifier", id);
        obj = AppServer.findAppServer(id);
        Assert.assertNotNull("Find method for 'AppServer' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'AppServer' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AppServerIntegrationTest.testFindAllAppServers() {
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", dod.getRandomAppServer());
        long count = AppServer.countAppServers();
        Assert.assertTrue("Too expensive to perform a find all test for 'AppServer', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<AppServer> result = AppServer.findAllAppServers();
        Assert.assertNotNull("Find all method for 'AppServer' illegally returned null", result);
        Assert.assertTrue("Find all method for 'AppServer' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AppServerIntegrationTest.testFindAppServerEntries() {
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", dod.getRandomAppServer());
        long count = AppServer.countAppServers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<AppServer> result = AppServer.findAppServerEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'AppServer' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'AppServer' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AppServerIntegrationTest.testFlush() {
        AppServer obj = dod.getRandomAppServer();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to provide an identifier", id);
        obj = AppServer.findAppServer(id);
        Assert.assertNotNull("Find method for 'AppServer' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAppServer(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'AppServer' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppServerIntegrationTest.testMergeUpdate() {
        AppServer obj = dod.getRandomAppServer();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to provide an identifier", id);
        obj = AppServer.findAppServer(id);
        boolean modified =  dod.modifyAppServer(obj);
        Integer currentVersion = obj.getVersion();
        AppServer merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'AppServer' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AppServerIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", dod.getRandomAppServer());
        AppServer obj = dod.getNewTransientAppServer(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'AppServer' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'AppServer' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'AppServer' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AppServerIntegrationTest.testRemove() {
        AppServer obj = dod.getRandomAppServer();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'AppServer' failed to provide an identifier", id);
        obj = AppServer.findAppServer(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'AppServer' with identifier '" + id + "'", AppServer.findAppServer(id));
    }
    
}
