// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.MBeanAttributeDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MBeanAttributeIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MBeanAttributeIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MBeanAttributeIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MBeanAttributeIntegrationTest: @Transactional;
    
    @Autowired
    private MBeanAttributeDataOnDemand MBeanAttributeIntegrationTest.dod;
    
    @Test
    public void MBeanAttributeIntegrationTest.testCountMBeanAttributes() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", dod.getRandomMBeanAttribute());
        long count = org.seforge.paas.monitor.domain.MBeanAttribute.countMBeanAttributes();
        org.junit.Assert.assertTrue("Counter for 'MBeanAttribute' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testFindMBeanAttribute() {
        org.seforge.paas.monitor.domain.MBeanAttribute obj = dod.getRandomMBeanAttribute();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttribute(id);
        org.junit.Assert.assertNotNull("Find method for 'MBeanAttribute' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MBeanAttribute' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testFindAllMBeanAttributes() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", dod.getRandomMBeanAttribute());
        long count = org.seforge.paas.monitor.domain.MBeanAttribute.countMBeanAttributes();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MBeanAttribute', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.seforge.paas.monitor.domain.MBeanAttribute> result = org.seforge.paas.monitor.domain.MBeanAttribute.findAllMBeanAttributes();
        org.junit.Assert.assertNotNull("Find all method for 'MBeanAttribute' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MBeanAttribute' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testFindMBeanAttributeEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", dod.getRandomMBeanAttribute());
        long count = org.seforge.paas.monitor.domain.MBeanAttribute.countMBeanAttributes();
        if (count > 20) count = 20;
        java.util.List<org.seforge.paas.monitor.domain.MBeanAttribute> result = org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttributeEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MBeanAttribute' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MBeanAttribute' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testFlush() {
        org.seforge.paas.monitor.domain.MBeanAttribute obj = dod.getRandomMBeanAttribute();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttribute(id);
        org.junit.Assert.assertNotNull("Find method for 'MBeanAttribute' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMBeanAttribute(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MBeanAttribute' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testMerge() {
        org.seforge.paas.monitor.domain.MBeanAttribute obj = dod.getRandomMBeanAttribute();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttribute(id);
        boolean modified =  dod.modifyMBeanAttribute(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.seforge.paas.monitor.domain.MBeanAttribute merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MBeanAttribute' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", dod.getRandomMBeanAttribute());
        org.seforge.paas.monitor.domain.MBeanAttribute obj = dod.getNewTransientMBeanAttribute(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MBeanAttribute' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MBeanAttribute' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MBeanAttributeIntegrationTest.testRemove() {
        org.seforge.paas.monitor.domain.MBeanAttribute obj = dod.getRandomMBeanAttribute();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBeanAttribute' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttribute(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MBeanAttribute' with identifier '" + id + "'", org.seforge.paas.monitor.domain.MBeanAttribute.findMBeanAttribute(id));
    }
    
}
