// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.MBeanDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MBeanIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MBeanIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MBeanIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MBeanIntegrationTest: @Transactional;
    
    @Autowired
    private MBeanDataOnDemand MBeanIntegrationTest.dod;
    
    @Test
    public void MBeanIntegrationTest.testCountMBeans() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", dod.getRandomMBean());
        long count = org.seforge.paas.monitor.domain.MBean.countMBeans();
        org.junit.Assert.assertTrue("Counter for 'MBean' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MBeanIntegrationTest.testFindMBean() {
        org.seforge.paas.monitor.domain.MBean obj = dod.getRandomMBean();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBean.findMBean(id);
        org.junit.Assert.assertNotNull("Find method for 'MBean' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MBean' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MBeanIntegrationTest.testFindAllMBeans() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", dod.getRandomMBean());
        long count = org.seforge.paas.monitor.domain.MBean.countMBeans();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MBean', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.seforge.paas.monitor.domain.MBean> result = org.seforge.paas.monitor.domain.MBean.findAllMBeans();
        org.junit.Assert.assertNotNull("Find all method for 'MBean' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MBean' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MBeanIntegrationTest.testFindMBeanEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", dod.getRandomMBean());
        long count = org.seforge.paas.monitor.domain.MBean.countMBeans();
        if (count > 20) count = 20;
        java.util.List<org.seforge.paas.monitor.domain.MBean> result = org.seforge.paas.monitor.domain.MBean.findMBeanEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MBean' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MBean' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MBeanIntegrationTest.testFlush() {
        org.seforge.paas.monitor.domain.MBean obj = dod.getRandomMBean();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBean.findMBean(id);
        org.junit.Assert.assertNotNull("Find method for 'MBean' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMBean(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MBean' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MBeanIntegrationTest.testMerge() {
        org.seforge.paas.monitor.domain.MBean obj = dod.getRandomMBean();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBean.findMBean(id);
        boolean modified =  dod.modifyMBean(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.seforge.paas.monitor.domain.MBean merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MBean' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MBeanIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", dod.getRandomMBean());
        org.seforge.paas.monitor.domain.MBean obj = dod.getNewTransientMBean(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MBean' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MBean' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MBeanIntegrationTest.testRemove() {
        org.seforge.paas.monitor.domain.MBean obj = dod.getRandomMBean();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MBean' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.MBean.findMBean(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MBean' with identifier '" + id + "'", org.seforge.paas.monitor.domain.MBean.findMBean(id));
    }
    
}
