// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.seforge.paas.monitor.domain.MBean;
import org.seforge.paas.monitor.domain.MBeanAttribute;
import org.seforge.paas.monitor.domain.MBeanDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MBeanAttributeDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MBeanAttributeDataOnDemand: @Component;
    
    private Random MBeanAttributeDataOnDemand.rnd = new SecureRandom();
    
    private List<MBeanAttribute> MBeanAttributeDataOnDemand.data;
    
    @Autowired
    private MBeanDataOnDemand MBeanAttributeDataOnDemand.mBeanDataOnDemand;
    
    public MBeanAttribute MBeanAttributeDataOnDemand.getNewTransientMBeanAttribute(int index) {
        MBeanAttribute obj = new MBeanAttribute();
        setDescription(obj, index);
        setMBean(obj, index);
        setName(obj, index);
        setType(obj, index);
        return obj;
    }
    
    public void MBeanAttributeDataOnDemand.setDescription(MBeanAttribute obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void MBeanAttributeDataOnDemand.setMBean(MBeanAttribute obj, int index) {
        MBean mBean = mBeanDataOnDemand.getRandomMBean();
        obj.setMBean(mBean);
    }
    
    public void MBeanAttributeDataOnDemand.setName(MBeanAttribute obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public void MBeanAttributeDataOnDemand.setType(MBeanAttribute obj, int index) {
        String type = "type_" + index;
        obj.setType(type);
    }
    
    public MBeanAttribute MBeanAttributeDataOnDemand.getSpecificMBeanAttribute(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        MBeanAttribute obj = data.get(index);
        return MBeanAttribute.findMBeanAttribute(obj.getId());
    }
    
    public MBeanAttribute MBeanAttributeDataOnDemand.getRandomMBeanAttribute() {
        init();
        MBeanAttribute obj = data.get(rnd.nextInt(data.size()));
        return MBeanAttribute.findMBeanAttribute(obj.getId());
    }
    
    public boolean MBeanAttributeDataOnDemand.modifyMBeanAttribute(MBeanAttribute obj) {
        return false;
    }
    
    public void MBeanAttributeDataOnDemand.init() {
        data = MBeanAttribute.findMBeanAttributeEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'MBeanAttribute' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<org.seforge.paas.monitor.domain.MBeanAttribute>();
        for (int i = 0; i < 10; i++) {
            MBeanAttribute obj = getNewTransientMBeanAttribute(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
