// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.Phym;
import org.seforge.paas.monitor.domain.PhymDataOnDemand;
import org.seforge.paas.monitor.domain.PhymIntegrationTest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PhymIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PhymIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PhymIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PhymIntegrationTest: @Transactional;
    
    @Autowired
    private PhymDataOnDemand PhymIntegrationTest.dod;
    
    @Test
    public void PhymIntegrationTest.testCountPhyms() {
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", dod.getRandomPhym());
        long count = Phym.countPhyms();
        Assert.assertTrue("Counter for 'Phym' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PhymIntegrationTest.testFindPhym() {
        Phym obj = dod.getRandomPhym();
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phym' failed to provide an identifier", id);
        obj = Phym.findPhym(id);
        Assert.assertNotNull("Find method for 'Phym' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Phym' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PhymIntegrationTest.testFindAllPhyms() {
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", dod.getRandomPhym());
        long count = Phym.countPhyms();
        Assert.assertTrue("Too expensive to perform a find all test for 'Phym', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Phym> result = Phym.findAllPhyms();
        Assert.assertNotNull("Find all method for 'Phym' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Phym' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PhymIntegrationTest.testFindPhymEntries() {
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", dod.getRandomPhym());
        long count = Phym.countPhyms();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Phym> result = Phym.findPhymEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Phym' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Phym' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PhymIntegrationTest.testFlush() {
        Phym obj = dod.getRandomPhym();
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phym' failed to provide an identifier", id);
        obj = Phym.findPhym(id);
        Assert.assertNotNull("Find method for 'Phym' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPhym(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Phym' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhymIntegrationTest.testMergeUpdate() {
        Phym obj = dod.getRandomPhym();
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phym' failed to provide an identifier", id);
        obj = Phym.findPhym(id);
        boolean modified =  dod.modifyPhym(obj);
        Integer currentVersion = obj.getVersion();
        Phym merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Phym' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PhymIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", dod.getRandomPhym());
        Phym obj = dod.getNewTransientPhym(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Phym' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Phym' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Phym' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PhymIntegrationTest.testRemove() {
        Phym obj = dod.getRandomPhym();
        Assert.assertNotNull("Data on demand for 'Phym' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Phym' failed to provide an identifier", id);
        obj = Phym.findPhym(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Phym' with identifier '" + id + "'", Phym.findPhym(id));
    }
    
}
