// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.seforge.paas.monitor.domain;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.seforge.paas.monitor.domain.VimDataOnDemand;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect VimIntegrationTest_Roo_IntegrationTest {
    
    declare @type: VimIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: VimIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: VimIntegrationTest: @Transactional;
    
    @Autowired
    private VimDataOnDemand VimIntegrationTest.dod;
    
    @Test
    public void VimIntegrationTest.testCountVims() {
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", dod.getRandomVim());
        long count = org.seforge.paas.monitor.domain.Vim.countVims();
        org.junit.Assert.assertTrue("Counter for 'Vim' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void VimIntegrationTest.testFindVim() {
        org.seforge.paas.monitor.domain.Vim obj = dod.getRandomVim();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.Vim.findVim(id);
        org.junit.Assert.assertNotNull("Find method for 'Vim' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Vim' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void VimIntegrationTest.testFindAllVims() {
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", dod.getRandomVim());
        long count = org.seforge.paas.monitor.domain.Vim.countVims();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Vim', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<org.seforge.paas.monitor.domain.Vim> result = org.seforge.paas.monitor.domain.Vim.findAllVims();
        org.junit.Assert.assertNotNull("Find all method for 'Vim' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Vim' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void VimIntegrationTest.testFindVimEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", dod.getRandomVim());
        long count = org.seforge.paas.monitor.domain.Vim.countVims();
        if (count > 20) count = 20;
        java.util.List<org.seforge.paas.monitor.domain.Vim> result = org.seforge.paas.monitor.domain.Vim.findVimEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Vim' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Vim' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void VimIntegrationTest.testFlush() {
        org.seforge.paas.monitor.domain.Vim obj = dod.getRandomVim();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.Vim.findVim(id);
        org.junit.Assert.assertNotNull("Find method for 'Vim' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyVim(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Vim' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VimIntegrationTest.testMerge() {
        org.seforge.paas.monitor.domain.Vim obj = dod.getRandomVim();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.Vim.findVim(id);
        boolean modified =  dod.modifyVim(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        org.seforge.paas.monitor.domain.Vim merged =  obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Vim' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void VimIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", dod.getRandomVim());
        org.seforge.paas.monitor.domain.Vim obj = dod.getNewTransientVim(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Vim' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Vim' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void VimIntegrationTest.testRemove() {
        org.seforge.paas.monitor.domain.Vim obj = dod.getRandomVim();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Vim' failed to provide an identifier", id);
        obj = org.seforge.paas.monitor.domain.Vim.findVim(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Vim' with identifier '" + id + "'", org.seforge.paas.monitor.domain.Vim.findVim(id));
    }
    
}
